Restored compatibility after Joint.None was removed.
Similar to:
https://github.com/ros/kdl_parser/pull/45
https://github.com/ros/kdl_parser/issues/44

When migrating to 20.04/Noetic/Python3 I ran into the same `AttributeError: type object 'PyKDL.Joint' has no attribute 'None'` error.  

This is pretty much just a copy of their fix.